PUT http://localhost:3001/api/blogs/5fcacd7371bc8b16ca81f0e2
Content-Type: application/json

{
	"title": "Another test",
	"author": "Robin Rendle",
	"url":"https://yle.fi/uutiset/osasto/news/finland_taking_in_11_underage_asylum_seekers_from_fire-devastated_greek_camp/11539172",
	"likes": 3
}